### ISSUE TITLE
移动端右上角的按钮，能不能控制哪些显示和隐藏呀？

### ISSUE THREAD

**Issue by 2903287116** [NameWjp/vue3-photo-preview#10]
![image](https://user-images.githubusercontent.com/83763949/177713887-d5d23900-84a1-4353-adb5-4ac76a336dcd.png)

**Comment by NameWjp** [comment]
可以  晚上回去弄弄

**Comment by 2903287116** [comment]
> 可以 晚上回去弄弄

感谢大佬！！！

**Comment by NameWjp** [comment]
这块我想了下，你可以用css选中里面的svg，设置 display:none 就可以隐藏了，不需要配置
