### ISSUE TITLE
移动端有时候出现图片不能左右滑动

### ISSUE THREAD

**Issue by 2903287116** [NameWjp/vue3-photo-preview#11]

**Comment by NameWjp** [comment]
能具体点吗？

**Comment by 2903287116** [comment]
> 能具体点吗？

屏幕左滑交互是上一张，右滑是下一张，有时候打开预览一张图片，左滑右滑图片不会切换

**Comment by NameWjp** [comment]
> > 能具体点吗？
> 
> 屏幕左滑交互是上一张，右滑是下一张，有时候打开预览一张图片，左滑右滑图片不会切换
我这边没复现出来。。或者有视频吗？

**Comment by 2903287116** [comment]
> > > 能具体点吗？
> > 
> > 
> > 这张幻灯片是滑片是
> > 复现下的，一张幻灯片，右边打开一张图片，左图不会是我现在没有出现。或者是幻灯片吗？

不好意思，样式全局添加了禁止鼠标事件，所以滑动不了，打扰了

**Comment by 2903287116** [comment]
> > > 能具体点吗？
> > 
> > 
> > 幻灯片是滑片
> > 复现下的，幻灯片是，右边打开这张图片，左图不会是我没有出现。或者是幻灯片吗？

不好意思，样式全局添加了禁止鼠标事件，所以不能左右滑动，打扰了
