### ISSUE TITLE
移动端也想像pc那样子的交互，显示前进后退按钮，这个怎么实现？

### ISSUE THREAD

**Issue by 2903287116** [NameWjp/vue3-photo-preview#12]

**Comment by 2903287116** [comment]
![image](https://user-images.githubusercontent.com/83763949/177741812-0fab7451-90e9-43bb-91f9-0cd01a7c8ae5.png)这个是pc

**Comment by 2903287116** [comment]
![image](https://user-images.githubusercontent.com/83763949/177741926-82584fd3-94dd-4fd3-9c6f-0662b438d8ef.png)
移动端不知道怎么调用上门的按钮出来

**Comment by 2903287116** [comment]
![image](https://user-images.githubusercontent.com/83763949/177742093-cd368522-65c9-43dc-ba8d-7ea28b89c6d9.png)
yi移动端不知道怎么调用上面的按钮出来

**Comment by NameWjp** [comment]
目前的设计就是这样的，考虑移动端屏幕小，完全可以用手势来操作，如果你非要显示的话可以 fork 一份自己打包，只需要修改下 [https://github.com/NameWjp/vue3-photo-preview/blob/master/src/PhotoSlider/index.vue#L77](https://github.com/NameWjp/vue3-photo-preview/blob/master/src/PhotoSlider/index.vue#L77) 里的代码，删掉判断就行了
