### ISSUE TITLE
全局img标签添加样式pointer-events: none;会导致移动端不能左右滑动图片，添加这个样式要禁止长按保存图片的功能

### ISSUE THREAD

**Issue by 2903287116** [NameWjp/vue3-photo-preview#13]

**Comment by 2903287116** [comment]
![image](https://user-images.githubusercontent.com/83763949/177743686-703669dd-ca0b-4de7-ba77-22cf53635f3d.png)
左右滑动事件能不能不要绑定在img上，用div包一层然后实现左右滑动交互

**Comment by NameWjp** [comment]
用css把 .PhotoSlider__Wrapper 下的图片 pointer-events 设置为 auto，因为预览图本身就没有长按保存的功能(使用 preventDefault 阻止了默认行为)，所以你也不需要设置它
