### ISSUE TITLE
下载有点问题哦图片放到CDN上面下载不了

### ISSUE THREAD

**Issue by liwenpmz** [NameWjp/vue3-photo-preview#14]

**Comment by NameWjp** [comment]
模拟的点击事件，不太可能有问题吧？是低版本浏览器吗，或者有没有复现的链接么

**Comment by liwenpmz** [comment]
点击下载之后浏览器url会直接跳到cnd里面

**Comment by liwenpmz** [comment]
把这个函数透露出来会比较好

**Comment by liwenpmz** [comment]
![image](https://user-images.githubusercontent.com/62593298/193002644-19ec715e-bc43-4824-a583-d7e9eacc678b.png)

**Comment by liwenpmz** [comment]
![image](https://user-images.githubusercontent.com/62593298/193002795-1023a204-a899-49a3-978c-9a45b338ceea.png)

**Comment by NameWjp** [comment]
查了下资料，确实有点问题，a标签download属性只能下载同源的图片，晚点改改

**Comment by NameWjp** [comment]
@liwenpmz 更新到 0.2.6 即可

**Comment by liwenpmz** [comment]
大佬牛逼
