### ISSUE TITLE
在移动端无法使用图片下载功能

### ISSUE THREAD

**Issue by zhisui** [NameWjp/vue3-photo-preview#16]

**Comment by NameWjp** [comment]
我自己测了下是可以的，能说下具体什么浏览器和版本吗

**Comment by zhisui** [comment]
我用 taro编译成h5形式的，将页面嵌入手机浙政钉里面点击下载没啥反应，如果用手机里面的浏览器打开是可以的&nbsp;


龙英
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 下午4:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NameWjp/vue3-photo-preview] 在移动端无法使用图片下载功能 (Issue #16)





 
我自己测了下是可以的，能说下具体什么浏览器和版本吗

**Comment by NameWjp** [comment]
调试模式可以看到报错吗？具体代码在 https://github.com/NameWjp/vue3-photo-preview/blob/master/src/PhotoSlider/index.vue#L250，你可以在 dist/vue3-photo-preview.esm.js 里面调试下，可能和 taro 有关？

**Comment by zhisui** [comment]
或许是吧，taro就是会出现各种各样莫名其妙的问题&nbsp;


龙英
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 下午5:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NameWjp/vue3-photo-preview] 在移动端无法使用图片下载功能 (Issue #16)





 
调试模式可以看到报错吗？具体代码在 https://github.com/NameWjp/vue3-photo-preview/blob/master/src/PhotoSlider/index.vue#L250，你可以在 dist/vue3-photo-preview.esm.js 里面调试下，可能和 taro 有关？

**Comment by zhisui** [comment]
我想请教下在example目录下运行报错是啥原因

&nbsp;


龙英
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 下午5:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NameWjp/vue3-photo-preview] 在移动端无法使用图片下载功能 (Issue #16)





 
调试模式可以看到报错吗？具体代码在 https://github.com/NameWjp/vue3-photo-preview/blob/master/src/PhotoSlider/index.vue#L250，你可以在 dist/vue3-photo-preview.esm.js 里面调试下，可能和 taro 有关？

**Comment by NameWjp** [comment]
报错信息有吗，是按照 本地开发调试 的步骤操作的吗

**Comment by zhisui** [comment]
打扰问下，图片下载功能是不是只能在浏览器打开下载


龙英
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NameWjp/vue3-photo-preview"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月27日(星期四) 中午1:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NameWjp/vue3-photo-preview] 在移动端无法使用图片下载功能 (Issue #16)





 
Closed #16 as completed.

**Comment by NameWjp** [comment]
可以确认下 URL 对象和 canvas 是否支持，不支持的话就不行

**Comment by NameWjp** [comment]
@zhisui 更新到 0.2.9 可以自定义图片下载方法了，你可以自己实现一个兼容的图片下载方法。
例子：[https://namewjp.github.io/vue3-photo-preview/?path=/docs/vue3-photo-preview--%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8B%E8%BD%BD%E6%96%B9%E6%B3%95](https://namewjp.github.io/vue3-photo-preview/?path=/docs/vue3-photo-preview--%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8B%E8%BD%BD%E6%96%B9%E6%B3%95)
