### ISSUE TITLE
移动端，多张图，点击预览图片后双指放大，有时候会触发滑动，直接切换到下一张图片

### ISSUE THREAD

**Issue by jijijiwinner** [NameWjp/vue3-photo-preview#17]

**Comment by jijijiwinner** [comment]
当有两个touchID时候，是否可以禁止左右滑动

**Comment by NameWjp** [comment]
现在逻辑是图片边界处于视口区域时是可以左右滑动的，猜测你的滑动是先触发左滑，再双指放大，这个时候确实可以切换照片。双指禁止滑动感觉不太合理

**Comment by NameWjp** [comment]
这个点周末有空改下

**Comment by jijijiwinner** [comment]
https://user-images.githubusercontent.com/19897884/203709778-ce4965d3-4661-4236-ba64-682ac40267c6.mov

**Comment by NameWjp** [comment]
@jijijiwinner 更新到0.2.8版本，现在图片未缩放并且双指缩放不会左右滑动了
