### ISSUE TITLE
操作按钮组件是否支持自定义位置

### ISSUE THREAD

**Issue by flingyp** [NameWjp/vue3-photo-preview#19]
![image](https://github.com/NameWjp/vue3-photo-preview/assets/57666140/886b06a9-6bbc-4ecc-8f20-6bfd71310ba5)

我更加喜欢将相关操作按钮放置在页面底部居中的位置，目前是通过重写样式来实现此功能。

组件是否可以添加相关的配置来实现这一效果？

**Comment by NameWjp** [comment]
每个人的喜好不太一样，暂时没想到如何通过一个配置满足所有人的需求，可能通过 css 覆盖是种好方法？

**Comment by flingyp** [comment]
> 每个人的喜好不太一样，暂时没想到如何通过一个配置满足所有人的需求，可能通过 css 覆盖是种好方法？

也对
