### ISSUE TITLE
手动开启预览

### ISSUE THREAD

**Issue by zhangguixin** [NameWjp/vue3-photo-preview#2]
希望手动开启预览 , 展示前图片地址需要异步请求

**Comment by NameWjp** [comment]
预览图片懒加载？

**Comment by zhangguixin** [comment]
预览图需要去阿里请求授权,拿到授权携带参数的图片地址后才允许访问资源 .  目前在预览图展开状态时,更新数据,好像并不能重新渲染

**Comment by NameWjp** [comment]
@zhangguixin 确实有点问题，现在是组件 mounted 时候收集 src，没有考虑 src 更新的情况。关于手动预览考虑加个参数控制，今天有空写一个版本

**Comment by NameWjp** [comment]
@zhangguixin 发布了 0.14  版本，会监听 src 的变化。手动控制预览的例子：[受控延迟预览](https://namewjp.github.io/vue3-photo-preview/?path=/docs/vue3-photo-preview--%E5%8F%97%E6%8E%A7%E5%BB%B6%E8%BF%9F%E9%A2%84%E8%A7%88)
