### ISSUE TITLE
排序异常

### ISSUE THREAD

**Issue by Carseason** [NameWjp/vue3-photo-preview#23]
<img width="1917" alt="image" src="https://github.com/NameWjp/vue3-photo-preview/assets/25239238/35085118-c570-45f3-95b3-4ff12cca69e4">

```
 "vue3-photo-preview": "^0.3.0"
```

使用 photo-provider 和 photo-consumer 时，默认打开图片预览时，图片预览的列排序异常

**Comment by NameWjp** [comment]
使用最新版本 0.3.2，https://github.com/NameWjp/vue3-photo-preview/commit/a4a6a430470c1c61001052a74462b03de9394af5 这里修复过了。如果还是有问题看能否给个复现的 demo

**Comment by Carseason** [comment]
似乎 0.3.2 还没发版？

**Comment by NameWjp** [comment]
> 似乎 0.3.2 还没发版？

不好意思，是 0.3.0 说错了，能否给个 demo 复现下，这两天有空看下

**Comment by Carseason** [comment]
似乎是 https://github.com/NameWjp/vue3-photo-preview/commit/a4a6a430470c1c61001052a74462b03de9394af5
里的       
```
items.sort((cur, next) => getElementIndex(children, cur.originRef) - getElementIndex(children, next.originRef)); 
```
方向错误? 
我改成
```
getElementIndex(children, next.originRef) - getElementIndex(children, cur.originRef)
```
即可

**Comment by Carseason** [comment]
应该是我的业务和组件一起使用有问题，空了我弄个demo看看
