### ISSUE TITLE
预览大图时，能否自定义预览第n张图片？

### ISSUE THREAD

**Issue by coderlyu** [NameWjp/vue3-photo-preview#24]
需求描述
1. 第一次点击，预览大图时，能否自定义跳转到第n张图去预览

**Comment by NameWjp** [comment]
https://namewjp.github.io/vue3-photo-preview/?path=/docs/vue3-photo-preview--%E5%8F%97%E6%8E%A7%E5%BB%B6%E8%BF%9F%E9%A2%84%E8%A7%88 可以参考下这里，使用 photo-slider 可以控制是否展示、展示第几张
