### ISSUE TITLE
图片是base64，加载时间会很长

### ISSUE THREAD

**Issue by wweggplant** [NameWjp/vue3-photo-preview#26]

**Comment by NameWjp** [comment]
base64 很大？有可复现的 demo 么

**Comment by wweggplant** [comment]
close掉吧，是因为之前intro也传了base64的src，太大导致的

`
      <photo-provider>
        <photo-consumer :intro="imageSrc" :src="imageSrc">
          <img :src="imageSrc" class="view-box" />
        </photo-consumer>
      </photo-provider>
`
