### ISSUE TITLE
通过按钮触发如何使用

### ISSUE THREAD

**Issue by nznl** [NameWjp/vue3-photo-preview#27]
请问通过按钮触发如何使用

**Comment by NameWjp** [comment]
> 请问通过按钮触发如何使用

https://namewjp.github.io/vue3-photo-preview/?path=/story/vue3-photo-preview--%E9%80%9A%E8%BF%87%E6%8C%89%E9%92%AE%E8%A7%A6%E5%8F%91

**Comment by nznl** [comment]
那个按钮没有点击事件触发呀

**Comment by NameWjp** [comment]
> 那个按钮没有点击事件触发呀

是的，内部自动绑定的，如果你想自己触发，看这里：https://namewjp.github.io/vue3-photo-preview/?path=/docs/vue3-photo-preview--%E5%8F%97%E6%8E%A7%E5%BB%B6%E8%BF%9F%E9%A2%84%E8%A7%88
