### ISSUE TITLE
点击图片的时候，没传任何参数

### ISSUE THREAD

**Issue by coder-free** [NameWjp/vue3-photo-preview#3]
我这里是在预览图片的时候，需要在图片上面做标记，就是鼠标点击的时候，需要获取到鼠标点击位置在图片上面的坐标，但是点击图片的回调里面没有任何参数

**Comment by coder-free** [comment]
我自己的问题，for in 没用好。。。

**Comment by NameWjp** [comment]
@coder-free 0.1.7版本加上 event 参数了，更新即可
