### ISSUE TITLE
希望可以把是否循环预览加上

### ISSUE THREAD

**Issue by LaiRui18** [NameWjp/vue3-photo-preview#4]

**Comment by NameWjp** [comment]
近期有空我看看

**Comment by NameWjp** [comment]
@LaiRui18 0.2.0 版本已经添加循环预览功能，详见：[循环预览](https://namewjp.github.io/vue3-photo-preview/?path=/docs/vue3-photo-preview--%E5%BE%AA%E7%8E%AF%E9%A2%84%E8%A7%88)
