### ISSUE TITLE
兼容问题，在苹果手机上，放大图片超过屏幕，左右移动会闪屏，并且不能跳下一张

### ISSUE THREAD

**Issue by LaiRui18** [NameWjp/vue3-photo-preview#5]
安卓手机上没有问题

**Comment by LaiRui18** [comment]
https://user-images.githubusercontent.com/29541432/156311883-76194254-029f-41b7-ad9b-04e8669d435c.mp4

**Comment by LaiRui18** [comment]
https://user-images.githubusercontent.com/29541432/156334711-c18fe7bc-f387-4c6a-b996-d567223b31ae.mp4

作者可以留个联系方式吗

**Comment by LaiRui18** [comment]
@NameWjp

**Comment by NameWjp** [comment]
@LaiRui18 不好意思，最近有点事没上github，你说的问题我今天看看

**Comment by LaiRui18** [comment]
@NameWjp 好的，非常感谢

**Comment by NameWjp** [comment]
@LaiRui18 更新版本到 0.2.1 即可，具体原因应该是 ios 的优化 bug，只考虑了 translate 而忘记考虑 scale 的影响，在 translate 超过一定值时不显示了，具体讨论可以查看：[https://www.v2ex.com/t/831846#reply26](https://www.v2ex.com/t/831846#reply26)
