### ISSUE TITLE
При смене позиции старые изображения остаются

### ISSUE THREAD

**Issue by atkisai** [NameWjp/vue3-photo-preview#6]
Привет, крутая галерея! У меня карточки товаров и когда я выполняю сортировку карточек, то при открытии изображения у карточек я вижу там другие изображения с других карточек, они случайным образом туда подмешиваются. Если все карточки поменять местами то у карточки будет ее изображение и изображение той карточки которая до этого была на ее месте. Как можно обновлять компонент галереи при смене позиции?

**Comment by NameWjp** [comment]
Спасибо за вопрос, это низкоуровневый вопрос, и я позабочусь об этом сегодня вечером.

**Comment by NameWjp** [comment]
Новая версия 0.2.2 решает проблему, но, похоже, что это баг в vue3, который не в Том порядке в списке обновленных изображений, и остается на тестирование

**Comment by atkisai** [comment]
> Новая версия 0.2.2 решает проблему, но, похоже, что это баг в vue3, который не в Том порядке в списке обновленных изображений, и остается на тестирование

хорошо, спасибо большое, попробую👍

**Comment by NameWjp** [comment]
Проблема обновления списка фотографий была решена с помощью версии 0.2.3, которая, надеюсь, поможет вам😄

**Comment by NameWjp** [comment]
@atkisai Используйте последнюю версию 0.2.3

**Comment by atkisai** [comment]
> Проблема обновления списка фотографий была решена с помощью версии 0.2.3, которая, надеюсь, поможет вамsmile
Это невероятно! Спасибо огромное, не верил что решится проблема. Все работает как надо! Отлично!
