### ISSUE TITLE
预览时加载图片

### ISSUE THREAD

**Issue by Bubbleioa** [NameWjp/vue3-photo-preview#8]
当前的版本在打开预览的时候会请求整个图片 url 列表，在图片多的时候会有很多流量浪费，希望能提供预览图片的时候再加载。

**Comment by NameWjp** [comment]
有空看看怎么改

**Comment by NameWjp** [comment]
@Bubbleioa 看了下不会呀，现在打开预览最多只会加载三张图片，切换后才会加载新图片，应该在能接受的范围吧。

**Comment by Bubbleioa** [comment]
了解了 刚刚更新到最新版本就解决了
